### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [WinkyN/prj-rev-bwfs-dasmoto#4]
Grade: **Needs Improvement**

Overall this project is working well and without error. It is missing some important features that are important to the specification of the project such as the images for the frames and paint. I would recommend going through the project once more, following the specification more closely so we don't miss crucial details such as images. After you've done this, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by WinkyN** [comment]
Thank you for this link. I will review this information and incorporate it in future projects.
